#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseSystems
wclean libso interfacialModels
wclean libso interfacialCompositionModels
wclean libso derivedFvPatchFields

wclean libso multiphaseSystem
wclean libso multiphaseCompressibleTurbulenceModels

wclean libso twoPhaseSystem
wclean libso twoPhaseCompressibleTurbulenceModels

#------------------------------------------------------------------------------
