#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

reactingTwoPhaseEulerFoam/Allwclean
reactingMultiphaseEulerFoam/Allwclean
wclean libso functionObjects

#------------------------------------------------------------------------------
