#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmakeLnInclude massTransferModels
wmake libso phasesSystem
wmake libso massTransferModels
wmake libso CompressibleMultiPhaseTurbulenceModels
wmake libso laserDTRM
wmake


# ----------------------------------------------------------------- end-of-file
